<!-- $Id: -->
<h5>Cookies Movements</h5>

<? if(isset($flash['notice'])):?>
    <div class="flash_notice">
        <div class="label">Note</div>
        <div class="content"><?=$flash['notice'];?></div>
    </div>
<? endif;?>
<? if(isset($flash['error'])):?>
    <div class="flash_error">
        <div class="label">Warning</div>
        <div class="content"><?=$flash['error'];?></div>
    </div>
<? endif;?>

<hr />

<? foreach($cookies as $cookie): ?>

    <a href="<?=URL::create('cookie', 'nuke', array('name'=>$cookie->getName()));?>">Remove</a>&nbsp;
    <b>Name:</b>&nbsp;<?=$cookie->getName();?>&nbsp;<b>Value:</b><?=$cookie->getValue();?><br />
    <b>DUMP: </b>&nbsp;<?=$cookie;?>
    <hr />

<? endforeach; ?>

<form name="add_cookie" method="post" action="<?=URL::create('cookie', 'add');?>">

<fieldset>
<legend>Add A new Cookie</legend>

<p>
    <label for="cookie[name]">Name : <sup style="color:red;">*</sup></label>
    <input type="text" name="cookie[name]" value="" />
</p>

<p>
    <label for="cookie[value]">Value : <sup style="color:red;">*</sup></label>
    <input type="text" name="cookie[value]" value="" />
</p>
<!--
<p>
    <label for="cookie[expire]">Expire</label>
    <input type="text" name="cookie[expire]" value="0" />
</p>

<p>
    <label for="cookie[path]">Path</label>
    <input type="text" name="cookie[path]" value="/" />
</p>

<p>
    <label for="cookie[domain]">Name</label>
    <input type="text" name="cookie[domain]" value="<?=$__server;?>" />
</p>

<p>
    <label for="cookie[secure]">Name</label>
    <input type="radio" name="cookie[secure]" value="0" />
    <input type="radio" name="cookie[secure]" value="1" />
</p>
    -->
<p><input name="submit" value="Add Cookie" type="submit" /></p>

</fieldset>

</form>

