<!-- $Id$ --> 
<h5>All Portfolios</h5>

<hr />

<? if(isset($flash['notice'])):?>
    <div class="flash_notice">
        <div class="label">Note</div>
        <div class="content"><?=$flash['notice'];?></div>
    </div>
<? endif;?>
<? if(isset($flash['error'])):?>
    <div class="flash_error">
        <div class="label">Warning</div>
        <div class="content"><?=$flash['error'];?></div>
    </div>
<? endif;?>

<? if($portfolios->size()==0):?>
  Didnt find any portfolio!
<? else: ?>
  <? foreach ($portfolios as $portfolio): ?>
    <div id="e_<?=$portfolio->id;?>" class="portfolio_<?=$portfolio->status == '1' ? 'online' : 'offline';?>">
      <a href="<?=URL::create('portfolio', 'edit',   array('id'=>$portfolio->id));?>">Edit</a> / 
      <a href="<?=URL::create('portfolio', 'delete', array('id'=>$portfolio->id));?>">Delete</a>&nbsp;
      <?=$portfolio->name;?>
    </div>
  <? endforeach; ?>
<? endif; ?>

<hr />

<a href="<?=URL::create('portfolio', 'add');?>">Add a new Portfolio</a>

