<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<!-- $Id$ -->
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <base href="http://localhost/eltodo/" />
        <link rel="stylesheet" href="stylesheet/eltodo.v0.2.css" />
        <title><?=$title;?></title>
    </head>

    <body>

        <div id="container">

            <div id="header">elTodo</div>

            <div id="sidebar">
                <h1>sidebar</h1>
                <ul>
                    <li>link one</li>
                    <li>link two</li>
                </ul>
            </div>

            <div id="content"><?=$content_for_layout;?></div>

            <div id="footer">Footer - | |- Footer </div>

        </div>

    </body>

</html>
