<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
     <head>
         <title>main</title>
         <base href="<?=$__server;?><?=$__base;?>/" />
         <link rel="stylesheet" href="stylesheet/medick.css" />
         <link rel="stylesheet" href="stylesheet/testor.css" />
         <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
     </head>
     <body>
        <div style="padding-bottom:15px">
        <a href="<?=URL::create('main');?>">Home</a> >> <a href="<?=URL::create($__controller);?>"><?=$__controller;?></a> >> <?=$__action;?></div>
        <?=$content_for_layout;?>
        <div style="float:right;"><a href="http://medick.locknet.ro">Medick</a> $v: <?=$__version;?> power.</div>
     </body>
</html>
