<h2>New Project</h2>
<!-- $Id: all.phtml 300 2005-12-12 19:51:31Z aurelian $ -->
<form action="<?=URL::create('project','create');?>" method="post">
    <fieldset>
        <legend>Create a new Project</legend>
        <?=ActiveRecordHelper::error_messages_for($project);?>
        <p><label for="project_name">Name</label><br />
        <?=FormHelper::text_field($project, 'name', array('maxlength'=>255,'size'=>35)); ?>
        </p>
        
        <p><label for="project_description">Description</label><br />
        <?=FormHelper::text_area($project, 'description', array('cols'=>40,'rows'=>20)); ?>
        </p>
        
        <?=Form::submit('submit', 'Submit', array('class'=>'submit-button')) ?>
        
    </fieldset>
</form>

