<h2>All Projects</h2>
<!-- $Id$ -->
<form action="<?=URL::create('project','create');?>" method="post">
    <div>
        <label>Create a new Project:</label>
        <?=Form::text('project_name', NULL, array('maxlength'=>255,'size'=>55)); ?>
        <?=Form::submit('submit', 'Submit') ?>
    </div>
</form>

<hr />

<? foreach($projects as $project): ?>
    <a 
        href="<?= URL::create('project', 'delete', array('id'=>$project->id));?>" 
        onclick="return confirm('Are you sure you want to delete the project <?=$project->name;?>');"
    >
    <img src="images/delete.png" border="0">
        </a>
    <?=$project->name;?><br />
<? endforeach;?>

<? if(!count($projects)):?>
    No projects found.
<? endif;?>

