<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Edit todo</title>
  </head>
  
  <body>
    <h2>Edit todo</h2>
  	<form action="<?= URL::create('todo','update');?>" method="post">
  	  <p>
  	    <?= Form::hidden('id', $todo->id); ?>
  	    <br /><label>Description: </label><?= Form::text('description', $todo->description, array('maxlength'=>255,'size'=>55)); ?><br /><label>Done: </label><?= Form::text('done', $todo->done, array('maxlength'=>1,'size'=>1)); ?><br />
  	    <?= Form::submit('submit', 'Edit Todo') ?>
  	  </p>
	</form>
  </body>  
</html>
