<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<!-- $Id$ -->
    <head>
        <title>Server Error!</title>
        <style type="text/css" media="all">
            body { margin: 3px; padding: 3px; border:1px solid red; font-size: .9em;
            font-family: "Lucida Grande", Helvetica, Tahoma, sans-serif; }
            h1 { text-align:center; }
            #container { margin: 3px; padding: 3px; }
        </style>
    </head>
    <body>
       <div id="container">
       <h1>Cannot process your request!</h1>
           <h2><?=get_class($error);?></h2>

           <strong>Message: <?=$error->getMessage();?></strong><br />
           <? if (method_exists($error,'getUserInfo') && $error->getUserInfo() != ''): ?>
                User Info: <?=$error->getUserInfo();?><br />
           <? endif; ?>
           <? if (method_exists($error,'getNativeError')): ?>
                Native Error: <?=$error->getNativeError();?><br />
           <? endif; ?>

           <strong>in</strong> <?=$error->getFile();?> at line: <?=$error->getLine();?>
           <hr />
           Backtrace:<br />
           <pre><?=$error->getTraceAsString();?></pre>
           <hr />
        </div>
    </body>
</html>
