<!-- $Id$ --> 
<h5>Lista Tone</h5>

<hr />

<? if(isset($flash['notice'])):?>
    <div class="flash_notice">
        <div class="label">Note</div>
        <div class="content"><?=$flash['notice'];?></div>
    </div>
<? endif;?>
<? if(isset($flash['error'])):?>
    <div class="flash_error">
        <div class="label">Warning</div>
        <div class="content"><?=$flash['error'];?></div>
    </div>
<? endif;?>

<? if($tone->size()==0):?>
  Nu am gasit nici un ``tone"!
<? else: ?>
  <? foreach ($tone as $entry): ?>
    <div id="e_<?=$entry->id;?>" class="entry_<?=$entry->status == '1' ? 'on' : 'off';?>">
      <a href="<?=URL::create('tone', 'edit',   array('id'=>$entry->id));?>">Edit</a> / 
      <a href="<?=URL::create('tone', 'delete', array('id'=>$entry->id));?>">Delete</a>&nbsp;
      <?=$entry->name;?>
    </div>
  <? endforeach; ?>
<? endif; ?>

<hr />

<a href="<?=URL::create('tone', 'add');?>">Adauga</a>

