<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<!-- $Id$ -->
  <head>
    <title>Server Error!</title>
    <style type="text/css" media="all">
      html * { padding:0; margin:0; }
      body * { padding:10px 20px; }
      body * * { padding:0; }
      body { font:small sans-serif; }
      body>div { border-bottom:1px solid #ddd; }
      h1 { font-weight:normal; }
      h2 { margin-bottom:.8em; }
      #container { background: #ffc; }
      #container h2 { font-weight: normal; color: #666; }
    </style>
  </head>
  <body>
       <div id="container">
       <h1>Cannot process your request!</h1>
           <h2><?=get_class($error);?></h2>

           <strong>Message: <?=$error->getMessage();?></strong><br />
           <? if (method_exists($error,'getUserInfo') && $error->getUserInfo() != ''): ?>
                User Info: <?=$error->getUserInfo();?><br />
           <? endif; ?>
           <? if (method_exists($error,'getNativeError')): ?>
                Native Error: <?=$error->getNativeError();?><br />
           <? endif; ?>

           <strong>in</strong> <?=$error->getFile();?> at line: <?=$error->getLine();?>
           <hr />
           Backtrace:<br />
           <pre><?=$error->getTraceAsString();?></pre>
           <hr />
           <h2>Request Info:</h2>
           <?=$request->toString();?>
        </div>
    </body>
</html>
