<?php

/** This file was autogenerated on 20/09/2005 13:09:45 by aurelian */

// todo_helper.php

function display_todos($items) {
    foreach ($items AS $todo):?>
        <div>
        <?=Form::checkbox(
            'done', 
            $todo->done, 
           'onclick="document.location.href=\''.URL::create('todo', 'checkbox', array('id'=>$todo->id)).'\'"');?>
                                
        <?=$todo->description;?>
        
        <?=$todo->project->name;?>
                    
        <a href="<?= URL::create('todo', 'edit', array('id'=>$todo->id));?>">Edit</a>
        <a 
            href="<?= URL::create('todo', 'delete', array('id'=>$todo->id));?>" 
            onclick="return confirm('Are you sure you want to delete this entry: <?=$todo->description;?>');"
        >
        Distroy
        </a>

        </div>
        <br />
    <? endforeach;
}
